config/routes.rb
KwIntranet::Application.routes.draw do
  resources :partners

  resources :clients
  root :to => "clients#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :razao_social, :cnpj, :telefones, :emails, :contatos, :area_atuacao, :ramo, :obs, :contrato
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :razao_social, :cnpj, :telefones, :emails, :contatos, :area_atuacao, :ramo, :obs, :contrato
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  uses_tiny_mce :options => {
                                :theme => 'advanced',
                                :theme_advanced_resizing => true,
                                :theme_advanced_resize_horizontal => false,
                                :plugins => %w{ table fullscreen }
                              }
                              
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])
    if @client.save
      redirect_to @client, :notice => "Successfully created client."
    else
      render :action => 'new'
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(params[:client])
      redirect_to @client, :notice  => "Successfully updated client."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_url, :notice => "Successfully destroyed client."
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  uses_tiny_mce :options => {
                                :theme => 'advanced',
                                :theme_advanced_resizing => true,
                                :theme_advanced_resize_horizontal => false,
                                :plugins => %w{ table fullscreen }
                              }
  def index
    @partners = Partner.all
  end

  def show
    @partner = Partner.find(params[:id])
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(params[:partner])
    if @partner.save
      redirect_to @partner, :notice => "Successfully created partner."
    else
      render :action => 'new'
    end
  end

  def edit
    @partner = Partner.find(params[:id])
  end

  def update
    @partner = Partner.find(params[:id])
    if @partner.update_attributes(params[:partner])
      redirect_to @partner, :notice  => "Successfully updated partner."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy
    redirect_to partners_url, :notice => "Successfully destroyed partner."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :razao_social %><br />
    <%= f.text_field :razao_social %>
  </p>
  <p>
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </p>
  <p>
    <%= f.label :telefones %><br />
    <%= f.text_area :telefones, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :emails %><br />
    <%= f.text_area :emails, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :contatos %><br />
    <%= f.text_area :contatos, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :area_atuacao %><br />
    <%= f.text_field :area_atuacao %>
  </p>
  <p>
    <%= f.label :ramo %><br />
    <%= f.text_field :ramo %>
  </p>
  <p>
    <%= f.label :obs %><br />
    <%= f.text_area :obs, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :contrato %><br />
    <%= f.text_field :contrato %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/clients/edit.html.erb
<% title "Edit Client" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @client %> |
  <%= link_to "View All", clients_path %>
</p>

app/views/clients/index.html.erb
<% title "Clients" %>

<table>
  <tr>
    <th>Razao Social</th>
    <th>Cnpj</th>
    <th>Telefones</th>
    <th>Emails</th>
    <th>Contatos</th>
    <th>Area Atuacao</th>
    <th>Ramo</th>
    <th>Obs</th>
    <th>Contrato</th>
  </tr>
  <% for client in @clients %>
    <tr>
      <td><%= client.razao_social %></td>
      <td><%= client.cnpj %></td>
      <td><%= client.telefones %></td>
      <td><%= client.emails %></td>
      <td><%= client.contatos %></td>
      <td><%= client.area_atuacao %></td>
      <td><%= client.ramo %></td>
      <td><%= client.obs %></td>
      <td><%= client.contrato %></td>
      <td><%= link_to "Show", client %></td>
      <td><%= link_to "Edit", edit_client_path(client) %></td>
      <td><%= link_to "Destroy", client, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Client", new_client_path %></p>

app/views/clients/new.html.erb
<% title "New Client" %>

<%= render 'form' %>

<p><%= link_to "Back to List", clients_path %></p>

app/views/clients/show.html.erb
<% title "Client" %>

<p>
  <strong>Razao Social:</strong>
  <%= @client.razao_social %>
</p>
<p>
  <strong>Cnpj:</strong>
  <%= @client.cnpj %>
</p>
<p>
  <strong>Telefones:</strong>
  <%= raw @client.telefones %>
</p>
<p>
  <strong>Emails:</strong>
  <%= raw @client.emails %>
</p>
<p>
  <strong>Contatos:</strong>
  <%= raw @client.contatos %>
</p>
<p>
  <strong>Area Atuacao:</strong>
  <%= @client.area_atuacao %>
</p>
<p>
  <strong>Ramo:</strong>
  <%= @client.ramo %>
</p>
<p>
  <strong>Obs:</strong>
  <%= raw @client.obs %>
</p>
<p>
  <strong>Contrato:</strong>
  <%= @client.contrato %>
</p>

<p>
  <%= link_to "Edit", edit_client_path(@client) %> |
  <%= link_to "Destroy", @client, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", clients_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "jquery" %>    
	<%= include_tiny_mce_if_needed %>
	<%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id="container">
		<%=link_to "Clientes", clients_path%> | 
		<%=link_to "Fornecedores", partners_path%>
	</div>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partners/_form.html.erb
<%= form_for @partner do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :razao_social %><br />
    <%= f.text_field :razao_social %>
  </p>
  <p>
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </p>
  <p>
    <%= f.label :telefones %><br />
    <%= f.text_area :telefones, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :emails %><br />
    <%= f.text_area :emails, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :contatos %><br />
    <%= f.text_area :contatos, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :area_atuacao %><br />
    <%= f.text_field :area_atuacao %>
  </p>
  <p>
    <%= f.label :ramo %><br />
    <%= f.text_field :ramo %>
  </p>
  <p>
    <%= f.label :obs %><br />
    <%= f.text_area :obs, :class => "mceEditor" %>
  </p>
  <p>
    <%= f.label :contrato %><br />
    <%= f.text_field :contrato %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/partners/edit.html.erb
<% title "Edit Partner" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @partner %> |
  <%= link_to "View All", partners_path %>
</p>

app/views/partners/index.html.erb
<% title "Partners" %>

<table>
  <tr>
    <th>Razao Social</th>
    <th>Cnpj</th>
    <th>Telefones</th>
    <th>Emails</th>
    <th>Contatos</th>
    <th>Area Atuacao</th>
    <th>Ramo</th>
    <th>Obs</th>
    <th>Contrato</th>
  </tr>
  <% for partner in @partners %>
    <tr>
      <td><%= partner.razao_social %></td>
      <td><%= partner.cnpj %></td>
      <td><%= partner.telefones %></td>
      <td><%= partner.emails %></td>
      <td><%= partner.contatos %></td>
      <td><%= partner.area_atuacao %></td>
      <td><%= partner.ramo %></td>
      <td><%= partner.obs %></td>
      <td><%= partner.contrato %></td>
      <td><%= link_to "Show", partner %></td>
      <td><%= link_to "Edit", edit_partner_path(partner) %></td>
      <td><%= link_to "Destroy", partner, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Partner", new_partner_path %></p>

app/views/partners/new.html.erb
<% title "New Partner" %>

<%= render 'form' %>

<p><%= link_to "Back to List", partners_path %></p>

app/views/partners/show.html.erb
<% title "Partner" %>

<p>
  <strong>Razao Social:</strong>
  <%= @partner.razao_social %>
</p>
<p>
  <strong>Cnpj:</strong>
  <%= @partner.cnpj %>
</p>
<p>
  <strong>Telefones:</strong>
  <%= raw @partner.telefones %>
</p>
<p>
  <strong>Emails:</strong>
  <%= raw @partner.emails %>
</p>
<p>
  <strong>Contatos:</strong>
  <%= raw @partner.contatos %>
</p>
<p>
  <strong>Area Atuacao:</strong>
  <%= @partner.area_atuacao %>
</p>
<p>
  <strong>Ramo:</strong>
  <%= @partner.ramo %>
</p>
<p>
  <strong>Obs:</strong>
  <%= raw @partner.obs %>
</p>
<p>
  <strong>Contrato:</strong>
  <%= @partner.contrato %>
</p>

<p>
  <%= link_to "Edit", edit_partner_path(@partner) %> |
  <%= link_to "Destroy", @partner, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", partners_path %>
</p>